import Head from 'next/head'
import Link from 'next/link';

import { Auth, API, graphqlOperation } from 'aws-amplify';
import { withAuthenticator } from '@aws-amplify/ui-react';
import { useEffect, useState } from 'react';





async function signOut() {
  try {
    await Auth.signOut();
  } catch (error) {
    console.log('error signing out: ', error);
  }
}

function Home() {
   const [user, setUser] = useState(null);
  useEffect(() => {
    checkUser()
   }, [])

  async function checkUser(){
    const user = await Auth.currentAuthenticatedUser()
    setUser(user)
  //   if (user) {
  //     // Create a new BasicUser record in your GraphQL API if the user doesn't already exist
  //     const { data } = await API.graphql(graphqlOperation(createBasicUser, { input: { username: user.username, email: user.attributes.email } }));
  //     console.log('created BasicUser', data.createBasicUser);
  //   }
  }

  if (!user) {
    return null;
  }

  return (
    <>
      <Head>
        <title>CantusIQ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className>
        <h1>Email: {user.attributes.email}</h1>
        <h1>Username: {user.attributes.preferred_username}</h1>

        

        <button onClick={signOut}>Sign out</button>
      </main>
    </>
  )
}

export default withAuthenticator(Home)
